language: minimal

services:
  - docker

env:
  global:
    - TEST_CMD='mvn test -B'
    - TRAVIS_SSH_KEY_TYPES='rsa,dsa,ecdsa'
    - DEPLOY_DIR='deploy'
    - REPOSITORY=$(basename "$TRAVIS_REPO_SLUG")

stages:
  - test
  - name: push
    if: branch = master
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - docker build --target build --tag "$REPOSITORY" .
        - docker run "$REPOSITORY" bash -c "$TEST_CMD"
    - stage: push
      script: bash "${DEPLOY_DIR}"/docker_push.sh
    - stage: deploy
      script:
        - docker build --tag "$REPOSITORY" .
        - ssh "${DEPLOY_USERNAME}"@"$DEPLOY_SERVER" < "${DEPLOY_DIR}"/deploy.sh
      before_install: bash "${DEPLOY_DIR}"/docker_push.sh
