language: minimal

services:
  - docker

env:
  global:
    - TEST_CMD='mvn test -B'
    - TRAVIS_SSH_KEY_TYPES='rsa,dsa,ecdsa'
    - DEPLOY_DIR='deploy'
    - REPOSITORY=$(basename "$TRAVIS_REPO_SLUG")

before_install:
  - eval "$(ssh-agent -s)"
  - bash "${DEPLOY_DIR}"/setup_ssh.sh

script:
  - docker build --target build --tag "$REPOSITORY" .
  - docker run "$REPOSITORY" bash -c "$TEST_CMD"

deploy:
  - provider: script
    script: bash "${DEPLOY_DIR}"/docker_push.sh
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: ssh "${DEPLOY_USERNAME}"@"$DEPLOY_SERVER" < "${DEPLOY_DIR}"/deploy.sh
    skip_cleanup: true
    on:
      branch: master
