language: java

jdk:
  - openjdk13

addons:
  ssh_known_hosts:
    - 159.65.47.132

before_install:
- openssl aes-256-cbc -K $encrypted_200a04de1233_key -iv $encrypted_200a04de1233_iv
  -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- ssh-add ./deploy_key
- ssh -i ./deploy_key root@159.65.47.132 pwd